### ISSUE TITLE
Archive page problem in 3.1.2 release

### ISSUE THREAD

**Issue by briho** [NateWr/bootstrap3#115]
When I install the 3.1.2 release of the plugin on a fresh installation of OJS 3.1.2 and try to view the journal archive page the journal fails and produces this error:

```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendpagesissueArchive"  on line 45 "{url|assign:"prevUrl" router=$smarty.const.ROUTE_PAGE page="issue" op="archive" path=$prevPage}" unknown modifier 'assign' <-- 
  thrown in /[XXX]/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 45

```

It doesn't seem to do this with other plugins, so I'm not entirely sure whether this is a problem with OJS or the Bootstrap 3 plugin.

**Comment by briho** [comment]
For what it's worth, this problem isn't specific to my local test installation. I just checked with our official PKP hosted journal and it fails to display an archive page as well when using Bootstrap 3.

**Comment by NateWr** [comment]
Thanks @briho, I've added a new release package for v3.1.2-1 of the Bootstrap3 theme. This will be compatible with OJS 3.1.2 and fix this error. https://github.com/NateWr/bootstrap3/releases/tag/3.1.2-1

@asmecher This can be added to the `plugins.xml` file with compatability 3.1.2. I realize, now, that matching version numbers is a bad idea because of cases like this, where a new theme version is needed but not a new OJS version. :/

**Comment by NateWr** [comment]
If you saw this message in the brief window when 3.1.2-1 was out, please use this release instead: https://github.com/NateWr/bootstrap3/releases/tag/3.1.2-2. Sorry for the confusion.

**Comment by asmecher** [comment]
Done -- but are you sure you got the right file? The release is named 3.1.2-2, but the filename is 3.1.2-1.
