### ISSUE TITLE
Settings > Website > Appearance messed up localization

### ISSUE THREAD

**Issue by eroesch** [NateWr/bootstrap3#125]
Hi @NateWr,

Thanks for your awesome work!! Much much appreciated!! :)

On my recent install, Settings > Website > Appearance for bootstrap3 seems to have messed up localization, see picture below. I have successfully used that version of the template a few months ago, but had to reinstall ojs. This time, I added bootstrap3 as a submodule into my ojs git repo.
I am using the latest ojs commit as of today for stable-3_1_2 and upgraded db schemas.
Any idea where that might be coming from, and what I could do to fix it?

<img width="639" alt="Screenshot 2019-06-21 21 24 45" src="https://user-images.githubusercontent.com/1738143/59949643-a3add200-946b-11e9-99f3-e2c85c79dc4a.png">

Thanks!

Etienne

**Comment by NateWr** [comment]
Hi @eroesch,

Hmm, I'm not sure. Can you double-check the version of Bootstrap3 that you're on? I think it should be v3.1.2-5.

Also, can you try another theme and see if you have any localization issues with that?

Are you running your site in English or another language?

Can you share the `locale.xml` file for the language you are using in `/plugins/generic/bootstrap3/locale`?

**Comment by eroesch** [comment]
Haha! That's it, because you're awesome and working ahead, I was already on branch 3.2, whereas I am using ojs 3.1.2! git checkout 3.1.2 saved the day.

The install instructions for the theme specify downloading a zip of the repo, and not cloned git into my ojs git as a submodule, which I have done without thinking too much about it. Do you foresee any issue with this?

Kind regards,

Etienne

**Comment by NateWr** [comment]
The `3.x` branches you find in the repo here do not necessarily match 1-to-1 with the `stable-3_1_2` branches you will find in ojs/pkp-lib. That's been my mistake, just because it's a different way of working.

What I would recommend is checking out the exact commit related to the release that you want. For example, the [3.1.2-5](https://github.com/NateWr/bootstrap3/releases/tag/3.1.2-5) release is pegged commit 9e95386. So if you run the following you'll get that release:

```
git checkout 9e95386
```

With future releases I plan to run the stable branches in the same way that they are done with the application repos. So I will have a `stable-3_2_0` branch and a `stable-3_2_1` branch and so on that you should be able to use. But for now you'll need to get the exact commit for each release.

**Comment by eroesch** [comment]
Awesome! Thanks!
