### ISSUE TITLE
Theme modification? 

### ISSUE THREAD

**Issue by navotera** [NateWr/bootstrap3#144]
Hi @NateWr 
What is the exact license of this theme, just make sure that this is the same as OJS license which is GNU licenses? 
Can I modify this theme? 

Thanks

**Comment by NateWr** [comment]
Hi @navotera! It's released under GPL v3 and you are permitted to take and modify it in whatever way you'd like. I've added the license to the project [here](https://github.com/NateWr/bootstrap3/blob/master/LICENSE) so there's no ambiguity.

You might want to explore the [theming guide](https://docs.pkp.sfu.ca/pkp-theming-guide/en/) if you haven't found it already. It may make more sense for you to use a child theme rather than customize this one, but whichever approach you find more useful.

**Comment by navotera** [comment]
Thank you so much NateWr.
