### ISSUE TITLE
getPageCount on array generating fatal error

### ISSUE THREAD

**Issue by jnugent** [NateWr/bootstrap3#167]
Reference:

https://forum.pkp.sfu.ca/t/bootstrap-3-php-fatal-error-uncaught-error-call-to-a-member-function-getpagecount-on-array

Seen in OJS 3.3.0-5

It seems that the $journals object in the indexSite.tpl template isn't an iterator, but rather an array.  It's counted correctly here:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/indexSite.tpl#L28

But not here:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/indexSite.tpl#L76

**Comment by NateWr** [comment]
Thanks, can you make a PR with the change?

**Comment by jnugent** [comment]
@NateWr I can easily handle the problem with the getPageCount on array, but I'm not sure what to do about the page info iterator inside that statement, because that will not work either.  Is there a better way to build page links when you only have an array, or is this going to require a more substantial rewrite?

**Comment by jnugent** [comment]
Looking at how it's implemented in the default template, there's no paging included.

**Comment by NateWr** [comment]
It looks like the actual pagination of results was removed as far back as 3.1.2: https://github.com/pkp/ojs/commit/bb5f1a1525c7e4457aa36095feff1a2c9f892d8b#diff-c6f951cafd142867658dc0b32c248a531f6f2ecdf5996c861c46d0af80bdc6ed. We've been fetching and displaying all journals on one page ever since, so I think you can remove the pagination from the template here.

**Comment by NateWr** [comment]
Merged #168. Thanks @jnugent!
