### ISSUE TITLE
Troubles with install

### ISSUE THREAD

**Issue by henkela** [NateWr/bootstrap3#32]
Hi,
I really like to see bootstrap in OJS, so many thanks for your efforts!
However, I cloned the repo to the appropriate folder named bootstrap3 and could find the theme in the website settings dialogue. But once activated the page is "naked"... No css, etc. 
Is there a brief summary of how to get going with the current state?

Best
Andreas

**Comment by joaoricardorm** [comment]
Same thing happening here too

**Comment by NateWr** [comment]
Hi to both. Sorry for the delay. I'm currently out of the office but will
reply as soon as I'm back. A few recent changes need to be made which I'll
update you on soon.

**Comment by NateWr** [comment]
Hi again. I'm glad you're interested in a Bootstrap3 theme. I'm hoping to encourage more community contributions.

The Theme API is currently undergoing a lot of work, so this theme will fall in-and-out of working order with OJS3's `master` branch. The big thing that's happening now is implementation of parent/child theme relations. See [the issue for the theme api](https://github.com/pkp/pkp-lib/issues/1468) as well as a [sample child theme](https://github.com/NateWr/default-child) I've thrown together.

I've updated the `bootstrap3` theme in this repo so it should be working. But the PRs haven't yet been merged. If you want to check it out before the changes are merged, see these PRS:

https://github.com/pkp/pkp-lib/pull/1519
https://github.com/pkp/ojs/pull/860

There's still a lot to be done so if you see something is missing in the bootstrap theme, please file an issue or PR. Many things are waiting to be done in the default OJS3 theme as well, since we're still putting together some of the key details.

**Comment by NateWr** [comment]
You may have heard that OJS 3.0 was officially released yesterday.

I've tidied up a few more issues in the Bootstrap3 theme and released version 1.0 today. Get it here:

https://github.com/NateWr/bootstrap3/releases

I'm looking forward to community contributions so please file issues and let me know how you get on with it. I'm sure there are some rough edges to be worked out.
